export const CATEGORIES = [
  { id: "social",     a: "Yksin",         b: "Yhdessä" },
  { id: "location",   a: "Ulkona",        b: "Sisällä" },
  { id: "intensity",  a: "Urheilua",      b: "Kevyttä" },
  { id: "cost",       a: "Ilmaista",      b: "Maksullista" },
  { id: "style",      a: "Luovaa",        b: "Strukturoitua" },
  { id: "commitment", a: "Säännöllistä",  b: "Satunnaista" },
];

export const HOBBIES = [
  {
    name: "Aamujooga",
    attrs: ["b", "b", "b", "b", "neutral", "b"],
    when: "Maanantai 1.6.",
    where: "Joogastudio Pranama",
  },
  {
    name: "Kaupunkiviljely",
    attrs: ["b", "a", "b", "a", "a", "b"],
    when: "Maanantai 1.6.",
    where: "Vallilan siirtolapuutarha",
  },
  {
    name: "Keramiikkapaja",
    attrs: ["neutral", "b", "b", "b", "a","b"],
    when: "Tiistai 2.6.",
    where: "Arabian taidekeskus",
  },
  {
    name: "Kiipeily",
    attrs: ["neutral", "b", "a", "b", "neutral", "neutral"],
    when: "Tiistai 2.6.",
    where: "Herttoniemen sisäkiipeilyhalli",
  },
  {
    name: "Öljyvärimaalaus",
    attrs: ["a", "b", "b", "b", "a", "b"],
    when: "Keskiviikko 3.6.",
    where: "Pikku-Huopalahden nuorisotalo",
  },
  {
    name: "Jalkapallo",
    attrs: ["b", "a", "a", "a", "b","b"],
    when: "Keskiviikko 3.6.",
    where: "Jätkänsaaren liikuntapuisto",
  },
  {
    name: "Filmivalokuvaus",
    attrs: ["a", "neutral", "b", "b", "a", "b"],
    when: "Torstai 4.6.",
    where: "Suomen valokuvataiteen museo",
  },
  {
    name: "Suomalaisen mytologian alkeiskurssi",
    attrs: ["b", "b", "b", "b", "neutral", "b"],
    when: "Torstai 4.6.",
    where: "Helsingin työväenopisto",
  },
  {
    name: "Tekstiilityön alkeet",
    attrs: ["neutral", "b", "b", "b", "a", "b"],
    when: "Perjantai 5.6.",
    where: "Taidesukellus - Ateljee Kamppi",
  },
  {
    name: "Klovneria",
    attrs: ["b", "b", "neutral", "b", "a", "b"],
    when: "Lauantai 6.6.",
    where: "Kellariteatteri Helsinki",
  },
  {
    name: "Verkkosivuohjelmoinnin alkeet",
    attrs: ["a", "b", "b", "b", "neutral", "b"],
    when: "Lauantai 6.6.",
    where: "Suomen Koodikoulu",
  },
  {
    name: "Pilates",
    attrs: ["b", "b", "a", "b", "b", "neutral"],
    when: "Sunnuntai 7.6.",
    where: "Pilates Circle Helsinki",
  },
  {
    name: "Rullaluistelu",
    attrs: ["a", "a", "a", "a", "b", "b"],
    when: "10.00 - 11.00",
    where: "Rulla-Espoo Ry",
  },
  {
    name: "Koripallo",
    attrs: ["b", "b", "a", "a", "b", "b"],
    when: "14.00 - 20.00",
    where: "Pasilan urheiluhalli",
  },
  {
    name: "Drag",
    attrs: ["b", "b", "b", "b", "a", "b"],
    when: "19.00 - 22.30",
    where: "Peacock Theatre",
  },
  {
    name: "Aamuhölkkä",
    attrs: ["a", "a", "a", "a", "b", "b"],
    when: "05.00 - 08.00",
    where: "Vantaan purujuoksurata",
  },
  {
    name: "Kitaransoiton alkeet",
    attrs: ["a", "b", "b", "b", "a", "b"],
    when: "11.00 - 15.00",
    where: "Töölön musiikkiopisto",
  },
  {
    name: "Tähtien ja tähtikuvioiden tunnistamista",
    attrs: ["neutral", "a", "b", "a", "b", "b"],
    when: "23.00 - 01.00",
    where: "Helsinki observatory",
  },
  {
    name: "Shakki",
    attrs: ["b", "b", "b", "a", "b", "b"],
    when: "09.00 - 12.00",
    where: "Helsingin Shakkiklubi",
  },
  {
    name: "Roolipelit",
    attrs: ["b", "b", "b", "a", "a", "b"],
    when: "13.30 - 16.30",
    where: "Halfmoon Game Cafe",
  },
  {
    name: "Marjastus",
    attrs: ["a", "a", "b", "a", "neutral", "b"],
    when: "16.00 - 21.00",
    where: "Riistavuoren metsäalue",
  },
];